ekf_filter_node:
  ros__parameters:
    frequency: 10.0 #30.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Odom-invoer
    odometry0: /odom
    odometry0_config: [true, true, false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]
    odometry0_differential: false
    odometry0_relative: false

    # GPS-invoer (via navsat_transform)
    odometry1: /odometry/gps
    odometry1_config: [true, true, false,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]
    odometry1_differential: false
    odometry1_relative: false
