navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    publish_filtered_gps: true

    use_odometry_yaw: false # true
    use_local_cartesian: false

    gps_topic: /fix
    odometry_topic: /odom
    gps_frame: gps_link
    world_frame: odom
    base_link_frame: base_link