ekf_filter_node:
  ros__parameters:

    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: true       # grasrobot rijdt alleen op vlak terrein
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom      # belangrijk: EKF publiceert odom â†’ base_link

    # Odom input (van je encoders/roover_odom_node)
    odom0: /odom
    odom0_config: [true,  true,  false,   # X, Y, Z
                   false, false, false,   # roll, pitch, yaw
                   true,  true,  false,   # Vx, Vy, Vz
                   false, false, true,    # roll_rate, pitch_rate, yaw_rate
                   false, false, false]   # ax, ay, az
    odom0_differential: false
    odom0_relative: false

    # IMU input (optioneel, als je IMU hebt!)
    # imu0: /imu
    # imu0_config: [false, false, false,   # X, Y, Z
    #               true,  true,  true,    # roll, pitch, yaw
    #               false, false, false,   # Vx, Vy, Vz
    #               false, false, true,    # roll_rate, pitch_rate, yaw_rate
    #               true,  true,  true]    # ax, ay, az
    # imu0_differential: false
    # imu0_relative: false

    # Output
    print_diagnostics: true
    use_control: false
    debug: false
