navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.0 # pas aan als je kompas corrigeert
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true # true
    wait_for_datum: false

    use_local_cartesian: false # laat dit op false tenzij je echt lokaal projectiesysteem wilt

     # Input topics
    imu0: /imu/data_raw
    odom0: /odometry/filtered
    gps0: /fix

    # Frames
    gps_frame: gps_link
    world_frame: map #odom 
    base_link_frame: base_link

    #Als je odom als wereld neemt, dan overschrijf je je eigen 
    #odometrie-frame en verlies je de koppeling naar GPS.